### ISSUE TITLE
Doesn't seem to support First-party Isolation

### ISSUE THREAD

**Issue by davidschlachter** [rotemdan/ExportCookies#5]
If First Party isolation is enabled (about:config -> privacy.firstparty.isolate to true, restart Firefox), the tool fails to export cookies.

To get the expected behaviour in this case, see [the Mozilla docs](https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/API/cookies/getAll) and this [commit from a similar extension](https://github.com/lennonhill/cookies-txt/pull/6/commits/7764a1bcff8475e5bc6a96bcc8c4ed036fafb758). I'm currently not set up to test this, otherwise would submit a PR.

**Comment by rotemdan** [comment]
Thanks. Fixed on 0.3.2 (new version now submitted to Mozilla addon site).
